version: "3.9"

services:
  postgres:
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: "shiva"
      POSTGRES_USER: "qwerty"
      POSTGRES_PASSWORD: "12qwaszx"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis-backend:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass 12qwaszx --loglevel warning
  rabbitmq-broker:
    restart: always
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=qwerty
      - RABBITMQ_DEFAULT_PASS=12qwaszx
